"""empty message

Revision ID: bfa3a3b1297a
Revises: 437f11ca7c2c
Create Date: 2020-09-06 16:20:52.149910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa3a3b1297a'
down_revision = '437f11ca7c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_cast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cast')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cast',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], name='cast_actor_id_fkey'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='cast_movie_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cast_pkey')
    )
    op.drop_table('movie_cast')
    # ### end Alembic commands ###
